feat: emit num
Meland-Inc/meland-unity pull request #100
Opened 2022-07-24 02:32 UTC by a412555466

依赖：https://github.com/Meland-Inc/meland-unity-ui/pull/12

2022-07-25 04:21 UTC, wxq127 requested changes
ReferencePool和objectPool用的很6，对性能要求严格，挺好的

2022-07-25 04:21 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitNumberManager.cs
> +    private static EmitNumberManager s_instance;
我们以后原则上都不要用单例 大家都约束好

2022-07-25 04:21 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitNumberBase.cs
> + * @Description: 发射对象基础 OnInit——>OnShow——>OnComplete——>OnHide——>Clear——>Release
good  这个时序说明很好 不过我猜测是先release 才clear把

2022-07-25 04:21 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitBattleNumberObject.cs
> +        if (_numberData != null)
隐藏的时候貌似tween没有停下来  下次回收利用时会继续tween吧

2022-07-25 04:21 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitNumberBase.cs
> +            GCom.Dispose();
从object池释放时这个调用后GCom被释放 但是没有看到重新激活重新生成的地方  只看到从ReferencePool池中出来生成  是因为release后就直接回ReferencePool池了吗

2022-07-25 04:21 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitNumberManager.cs
> +        _instancePool.Unspawn(emitNumber.GCom);
这句我没看懂 激活的是EmitNumberBase  但是这里失效的是GCompont

2022-07-25 06:27 UTC, a412555466 commented on Assets/Src/Module/Network/SocketProtobufChannelHelper.cs
> +        GameChannelPacket packet = ReferencePool.Acquire<GameChannelPacket>();
使用EventPool.Fire抛出的事件，最后会被回收。想了一下。应该还有几处也这样做的，要改，

2022-07-25 06:28 UTC, a412555466 commented on Assets/Src/Module/EmitNumber/EmitBattleNumberObject.cs
> +    public static float MOVE_TIME = 1f;  //移动时间
没报呀。

2022-07-25 06:34 UTC, a412555466 commented on Assets/Src/Module/EmitNumber/EmitBattleNumberObject.cs
> +        float distance = Vector3.Distance(_numberData.Pos, Camera.main.transform.position);
这一句没必要提吧

2022-07-25 06:48 UTC, a412555466 commented on Assets/Src/Module/EmitNumber/EmitNumberBase.cs
> + * @Description: 发射对象基础 OnInit——>OnShow——>OnComplete——>OnHide——>Clear——>Release
确实，写错了

2022-07-25 06:48 UTC, a412555466 commented on Assets/Src/Module/EmitNumber/EmitBattleNumberObject.cs
> +        if (_numberData != null)
使用前会重置tween

2022-07-25 06:51 UTC, a412555466 commented on Assets/Src/Module/EmitNumber/EmitNumberBase.cs
> +            GCom.Dispose();
释放时，得销毁GCom这个有啥问题么？没太懂你的意思

2022-07-25 06:54 UTC, a412555466 commented on Assets/Src/Module/EmitNumber/EmitNumberManager.cs
> +        _instancePool.Unspawn(emitNumber.GCom);
GCom其实是EmitNumberBase得Target。所以回收时可以使用GCom回收

2022-07-25 07:04 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitBattleNumberObject.cs
> +    public static float MOVE_TIME = 1f;  //移动时间
那可能你分析器还没分析到或者ide bug了  静态的都是需要s_的   你再检查下

2022-07-25 07:07 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitBattleNumberObject.cs
> +    public static float MOVE_TIME = 1f;  //移动时间
确实  只有私有的要求s_打头  那你这里也是不对的  前后意图不一样 前期我对语法要求会比较严格

2022-07-25 07:10 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitBattleNumberObject.cs
> +        float distance = Vector3.Distance(_numberData.Pos, Camera.main.transform.position);
我说的是下面一起的三句 你自己看要不要把   话说这三句一共是什么效果？

2022-07-25 07:11 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitBattleNumberObject.cs
> +        if (_numberData != null)
隐藏时也需要重置  逻辑更加严谨且不容易失控

2022-07-25 07:12 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitNumberBase.cs
> +            GCom.Dispose();
我的意思应该是成对的  有释放就有激活 没看到激活

2022-07-25 07:13 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitNumberManager.cs
> +        _instancePool.Unspawn(emitNumber.GCom);
所以这个EmitNumberBase没有回收？

2022-07-25 07:14 UTC, a412555466 commented on Assets/Src/Module/EmitNumber/EmitBattleNumberObject.cs
> +        float distance = Vector3.Distance(_numberData.Pos, Camera.main.transform.position);
这个就是数字UI随着镜头的距离，在一定范围内缩放，我觉得其他地方应该不会用到。也不一定要这种效果

2022-07-25 07:16 UTC, a412555466 commented on Assets/Src/Module/EmitNumber/EmitNumberBase.cs
> +            GCom.Dispose();
GCom 是new出来的

2022-07-25 07:18 UTC, a412555466 commented on Assets/Src/Module/EmitNumber/EmitNumberManager.cs
> +        _instancePool.Unspawn(emitNumber.GCom);
EmitNumberBase继承ObjectBase，会被对象池回收的。

2022-07-25 07:22 UTC, wxq127 commented on Assets/Src/Module/Network/SocketProtobufChannelHelper.cs
> +        GameChannelPacket packet = ReferencePool.Acquire<GameChannelPacket>();
看了 Fire中指回收了 那个EventNode  里面我们的这个对象是没有回池的

2022-07-26 01:21 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitNumberBase.cs
> +            GCom.Dispose();
没看到new的地方  只看到出ReferencePool有new

2022-07-26 01:26 UTC, wxq127 commented on Assets/Src/Module/EmitNumber/EmitNumberManager.cs
> +        _instancePool.Unspawn(emitNumber.GCom);
感觉逻辑不大对：
- EmitNumberBase如果只是隐藏，没有Unspawn 计数是不会少的 怎么触发回收
- 即使会自动回收，由于这里会将GCom释放，在base回收之前如果重新激活，GCom就找不到了

2022-07-26 05:56 UTC, wxq127 approved these changes

2022-07-26 06:11 UTC, merged