Feat:web http,quick login
Meland-Inc/meland-unity pull request #18
Opened 2022-05-24 05:37 UTC by lmangit

2022-05-25 09:09 UTC, wxq127 requested changes

2022-05-25 09:09 UTC, wxq127 commented on Assets/Src/Module/Login/LoginDefine.cs
> +            TimeStamp = (TimeUtil.GetTimeStamp() / 1000).ToString(),
这个除1000参考egret里面GameTimerManager.MILLISECOND_TO_SECOND   可以定义在TimeDefine里面 不要放工具  工具往往是方法

2022-05-25 09:11 UTC, lmangit commented on Assets/Src/Util/TimeUtil.cs
> +        DateTime dtFrom = new(1970, 1, 1, 0, 0, 0, 0);
阔以

2022-05-25 09:15 UTC, lmangit commented on Assets/Src/Util/MelandUtil.cs
> +            _ = sBuilder.Append(data[i].ToString("x2"));
应该是统一的md5算法，不同语言实现，用测试数据验证过了，一样的输入会有一样的输出

2022-05-25 09:19 UTC, lmangit commented on Assets/Src/Module/HttpAction/LoginAction.cs
> +public class LoginAction : HttpChannelNetMsgActionBase<LoginReq, LoginRsp>
嗯，这个是测试文件，后面我把他删了

2022-05-25 09:19 UTC, lmangit commented on Assets/Src/Module/HttpAction/LoginAction.cs
> +    protected override string ApiRoot => "localhost:8080/";
同上

2022-05-25 09:19 UTC, lmangit commented on Assets/Src/Framework/Network/HttpPacketDefine.cs
> +    public class GetPlayerRsp : HttpRspBase
有道理

2022-05-26 04:43 UTC, lmangit commented on Assets/Src/Framework/Network/ChannelPacket.cs
> +        //to do
框架在 Clear后还会访问ChannelPacket的Id，这个Id是通过TransferData访问的，而且这个TransferData也会跟着对象本身引起断开儿断开，这里不置空也是可以的

2022-05-26 04:53 UTC, lmangit commented on Assets/Src/Module/HttpAction/SigninPlayerAction.cs
> +public class SigninPlayerAction : GameChannelNetMsgRActionBase<Bian.SigninPlayerRequest, Bian.SigninPlayerResponse>
好

2022-05-26 04:55 UTC, lmangit commented on Assets/Src/Module/Network/Channel/GameChannel/GameChannelNetMsgTActionBase.cs
> +        //empty
hao

2022-05-26 06:16 UTC, lmangit commented on Assets/Src/Framework/Network/WebHttpNetworkChannel.cs
> +                url += item.Key + "=" + item.Value + "&";
好，下次改

2022-05-26 06:43 UTC, wxq127 approved these changes

2022-05-26 07:18 UTC, merged