feat:egret_game_web
Meland-Inc/meland-unity pull request #29
Opened 2022-05-31 13:37 UTC by a412555466

依赖：https://github.com/Meland-Inc/egret-planet/pull/526
依赖：https://github.com/Meland-Inc/meland-unity-ui/pull/2

2022-06-06 03:26 UTC, wxq127 requested changes
以工具命名和不走统一架构需要提升

2022-06-06 03:26 UTC, wxq127 commented on Assets/Src/Framework/Egret/Action/QuizCreateRoomAction.cs
> +                return false;
我看到只要是发了error 没有一个地方打印或者处理  子类和基类都没处理 这样设计不合理吧 如果想统一处理可以在基类统一处理一下哇

2022-06-06 05:51 UTC, a412555466 commented on Assets/Src/Module/Main/FormMain.cs
> +        btnAnswer.AddEventListener("onTouchEnd", () =>
ok

2022-06-06 05:51 UTC, a412555466 commented on Assets/Src/Module/Main/FormMain.cs
> +            int row = int.Parse(rowInput.text);
ok

2022-06-06 05:51 UTC, a412555466 commented on Assets/Src/Framework/Egret/EgretMessageDefine.cs
> +    public class LoginResponse : Message
可以·

2022-06-06 06:02 UTC, a412555466 commented on Assets/Src/Framework/Egret/EgretDefine.cs
> +public sealed class EgretDefine
我最开始设计就是单纯和egret那边通讯呀，所以就直接叫egret

2022-06-06 06:03 UTC, a412555466 commented on Assets/Src/Framework/Egret/EgretDefine.cs
> +    public enum eEgretEnableMode
要和白鹭那边界面id对上，所以这里id是固定的

2022-06-06 06:03 UTC, a412555466 commented on Assets/Src/Framework/Egret/EgretMsgNetwork.cs
> +public class EgretMsgNetwork
设计之初只是单纯和白鹭那边通讯，就不想耦合进现在的网络通讯里面

2022-06-06 06:04 UTC, a412555466 commented on Assets/Src/Framework/Egret/EgretMsgNetwork.cs
> +    private int _seqId;
同上

2022-06-06 06:04 UTC, a412555466 commented on Assets/Src/Framework/Egret/EgretMsgNetworkHelper.cs
> +public class EgretMsgNetworkHelper
同上

2022-06-06 06:53 UTC, a412555466 commented on Assets/Src/Framework/Egret/EgretGameCenter.cs
> +                visible = item.Value;
visible 初始化不是false么？有啥bug？

2022-06-06 06:58 UTC, a412555466 commented on Assets/Src/Framework/Egret/Action/QuizCreateRoomAction.cs
> +                return false;
白鹭那边直接返回创建成功，暂时没有错误处理，后面有了再加

2022-06-06 06:59 UTC, a412555466 commented on Assets/Src/Framework/Egret/TAtion/TEgretReadyAction.cs
> +            BasicModule.EgretGameCenter.EgretReady();
阔以。我发个事件

2022-06-06 07:10 UTC, wxq127 commented on Assets/Src/Framework/Egret/EgretDefine.cs
> +public sealed class EgretDefine
也不能叫白鹭哇 任何业务都不要和工具名耦合  你可以叫老web版本 2dweb版本都可以

2022-06-06 07:11 UTC, wxq127 commented on Assets/Src/Framework/Egret/EgretDefine.cs
> +public sealed class EgretDefine
而且我看你这个其实就是runtime协议 只是现在runtime协议接的白鹭接口调用 将来只是改底层走江哥sdk调用而已  从业务上本质是一件事情 只是现在调用的sdk不一样

2022-06-06 07:15 UTC, wxq127 commented on Assets/Src/Framework/Egret/EgretMsgNetwork.cs
> +public class EgretMsgNetwork
不管你和谁通信 理论上只要你和外部通信了就要走统一一套  到时候会统一做弱网菊花这些 还有协议队列策略这些  不过事实是接入统一一套确实成本会高出一点点 所以临时代码不那么严格要求 但是你这个代码我感觉会持续很长一段时间 也许一直存在都说不定

2022-06-06 07:16 UTC, wxq127 commented on Assets/Src/Framework/Egret/EgretMsgNetworkHelper.cs
> +public class EgretMsgNetworkHelper
你这个helper和框架的helper的概念已经完全不一样了 他的是处理序列化的

2022-06-06 07:32 UTC, wxq127 commented on Assets/Src/Framework/Egret/EgretGameCenter.cs
> +                visible = item.Value;
看错了 没看到上面的```bool visible = false;```

2022-06-07 03:29 UTC, wxq127 approved these changes
runtimeCenter和runtimeChannel解耦的不错 通过消息告诉频道收到消息了

2022-06-07 03:40 UTC, merged