feat：sound extension
Meland-Inc/meland-unity pull request #34
Opened 2022-06-07 12:10 UTC by a412555466

2022-06-09 08:18 UTC, wxq127 requested changes
需要注意一下 常量里面同组的能用枚举就用枚举

2022-06-09 08:18 UTC, wxq127 commented on Assets/Src/Csv/DataTableExtension.cs
> +        dataTable.ReadData(dataTableAssetName, MConstant.AssetPriority.DATA_TABLE_ASSET, userData);
主干有定义加载优先级的地方了 你改下位置  你的pr和主干已经有冲突了 反正要rebase的

2022-06-09 08:18 UTC, wxq127 commented on Assets/Src/Framework/Definition/MConstant/MConstant.SoundGroupType.cs
> +public static partial class MConstant
主干上已经有个GlobalDefine了 我们统一按照那个格式改下 你pr冲突了 需要rebase的

2022-06-09 08:18 UTC, wxq127 commented on Assets/Src/Framework/Definition/MConstant/MConstant.SoundGroupType.cs
> +        public const string MUSIC = "Music";
我感觉你这个可以用枚举吧

2022-06-09 08:18 UTC, wxq127 commented on Assets/Src/Framework/Definition/MConstant/MConstant.AssetPriority.cs
> +        public const int DATA_TABLE_ASSET = 100;
按照主干的AssetDefine里面统一使用枚举

2022-06-09 08:18 UTC, wxq127 commented on Assets/Src/Framework/Extension/UnityGameFramework/SoundExtension.cs
> +        return soundComponent.PlaySound(soundAssetName, MConstant.SoundGroupType.SOUND, MConstant.AssetPriority.SOUND_ASSET, playSoundParams, bindingEntity != null ? bindingEntity : null, userData);
```bindingEntity != null ? bindingEntity : null```貌似和```bindingEntity```是等价的吧

2022-06-09 08:18 UTC, wxq127 commented on Assets/Src/Framework/Extension/UnityGameFramework/SoundExtension.cs
> +    public static int? PlaySound(this SoundComponent soundComponent, string soundAssetName, PlaySoundParams playSoundParams, Entity bindingEntity = null, object userData = null)
可以哇 重载外部自己给参数 不错

2022-06-09 08:18 UTC, wxq127 commented on Assets/Src/Framework/Extension/UnityGameFramework/SoundExtension.cs
> +        return soundComponent.PlaySound(soundAssetName, MConstant.SoundGroupType.SOUND, MConstant.AssetPriority.SOUND_ASSET, playSoundParams, bindingEntity != null ? bindingEntity : null, userData);
```bindingEntity != null ? bindingEntity : null```同上

2022-06-13 01:32 UTC, a412555466 commented on Assets/Src/Csv/DataTableExtension.cs
> +        dataTable.ReadData(dataTableAssetName, MConstant.AssetPriority.DATA_TABLE_ASSET, userData);
好

2022-06-13 01:32 UTC, a412555466 commented on Assets/Src/Framework/Definition/MConstant/MConstant.SoundGroupType.cs
> +public static partial class MConstant
阔以

2022-06-13 01:33 UTC, a412555466 commented on Assets/Src/Framework/Definition/MConstant/MConstant.AssetPriority.cs
> +        public const int DATA_TABLE_ASSET = 100;
嗯

2022-06-13 01:33 UTC, a412555466 commented on Assets/Src/Framework/Extension/UnityGameFramework/SoundExtension.cs
> +        return soundComponent.PlaySound(soundAssetName, MConstant.SoundGroupType.SOUND, MConstant.AssetPriority.SOUND_ASSET, playSoundParams, bindingEntity != null ? bindingEntity : null, userData);
确实，我改改

2022-06-13 01:33 UTC, a412555466 commented on Assets/Src/Framework/Extension/UnityGameFramework/SoundExtension.cs
> +        return soundComponent.PlaySound(soundAssetName, MConstant.SoundGroupType.SOUND, MConstant.AssetPriority.SOUND_ASSET, playSoundParams, bindingEntity != null ? bindingEntity : null, userData);
1

2022-06-13 01:49 UTC, a412555466 commented on Assets/Src/Framework/Definition/MConstant/MConstant.SoundGroupType.cs
> +        public const string MUSIC = "Music";
也可以

2022-06-13 02:44 UTC, wxq127 requested changes

2022-06-13 02:44 UTC, wxq127 commented on Assets/Src/Module/Resource/AssetDefine.cs
> +public enum SoundGroupType : string
枚举名 没按统一规范 改下

2022-06-13 02:44 UTC, wxq127 commented on Assets/Src/Module/Resource/AssetDefine.cs
> +public enum SoundGroupType : string
你这个:string会报错吧   c# 不支持

2022-06-13 02:44 UTC, wxq127 commented on Assets/Src/Module/Resource/AssetDefine.cs
> +public enum SoundGroupType : string
其实声音这么大模块 可以自己定义一个deine  不用挤到资源加载这里  也不搭噶哇

2022-06-13 03:58 UTC, wxq127 approved these changes

2022-06-13 03:58 UTC, merged