Feat:create role
Meland-Inc/meland-unity pull request #41
Opened 2022-06-14 13:21 UTC by lmangit

2022-06-30 08:33 UTC, wxq127 requested changes
日志很全，代码也很规范，抽离LoginChannel也理解到位了

2022-06-30 08:33 UTC, wxq127 commented on Assets/Src/Module/Common/MLoader.cs
> +        GFEntry.Resource.UnloadAsset(url);
这样是卸不掉资源的  rebase主干后使用正确的卸载接口

2022-06-30 08:33 UTC, wxq127 commented on Assets/Src/Module/Common/MLoader.cs
> +            Texture2D tex = await GFEntry.Resource.AwaitLoadAsset<Texture2D>(url);
会和主干冲突 rebase后使用新的正确的资源加载接口和卸载

2022-06-30 08:33 UTC, wxq127 commented on Assets/Src/Module/Common/MLoader.cs
> +public class MLoader : GLoader
所以这个类的作用是为了走我们的资源加载对吧

2022-06-30 08:33 UTC, wxq127 commented on Assets/Src/Module/CreateRole/FormCreateRole.cs
> +        return name.Replace(@"[\u0391-\uFFE5]", "aa").Length;
其实可以抽一个统一计算字节的工具 而且循环计算都比这个性能更好

2022-06-30 08:33 UTC, wxq127 commented on Assets/Src/Module/Login/UI/FormLogin.cs
> +        // BasicModule.LoginCenter.SetUserID(userID);
这个类不需要就删掉吧 简洁一点

2022-06-30 08:33 UTC, wxq127 commented on Assets/Src/Module/Login/LoginChannelBase.cs
>      public void LoginWithAccount(string account, string password)
和接口一样 到时候一起删掉

2022-06-30 08:33 UTC, wxq127 commented on Assets/Src/Module/Login/LoginChannelDebug.cs
> +    public override void Register(string account, string userName, string password)
到时候和接口一起删掉

2022-06-30 08:33 UTC, wxq127 commented on Assets/Src/Module/Login/LoginChannelRuntime.cs
> +    public override void Register(string account, string userName, string password)
到时候和接口一起删掉

2022-06-30 13:38 UTC, lmangit commented on Assets/Src/Module/Login/UI/FormLogin.cs
> +        // BasicModule.LoginCenter.SetUserID(userID);
ok

2022-06-30 13:47 UTC, lmangit commented on Assets/Src/Module/CreateRole/FormCreateRole.cs
> +        return name.Replace(@"[\u0391-\uFFE5]", "aa").Length;
哈哈，确实，我直接搬过来的，没注意细看

2022-07-01 05:03 UTC, wxq127 requested changes

2022-07-01 05:03 UTC, wxq127 commented on Assets/Src/Util/MelandUtil.cs
> +    public static int GetTextNameLen(string name)
不要放到这个工具里  这个工具本身也不应该叫MelandUtil  需要具体点  否则其他人查不到这些工具  像你这个可以叫 StringUtil 或者别的名字

2022-07-01 05:05 UTC, wxq127 commented on Assets/Src/Util/MelandUtil.cs
> +            len += IsChinese(name[i]) ? 2 : 1;
没有别的库可以用对吧  只能我们自己原始写对吗

2022-07-01 05:34 UTC, lmangit commented on Assets/Src/Util/MelandUtil.cs
> +            len += IsChinese(name[i]) ? 2 : 1;
没去细找

2022-07-01 07:08 UTC, lmangit commented on Assets/Src/Module/Common/MLoader.cs
> +        GFEntry.Resource.UnloadAsset(url);
ok

2022-07-01 07:08 UTC, lmangit commented on Assets/Src/Module/Common/MLoader.cs
> +            Texture2D tex = await GFEntry.Resource.AwaitLoadAsset<Texture2D>(url);
ok

2022-07-01 07:08 UTC, lmangit commented on Assets/Src/Module/Common/MLoader.cs
> +public class MLoader : GLoader
是的

2022-07-01 07:10 UTC, lmangit commented on Assets/Src/Framework/Runtime/Action/LoginAction.cs
> +            OnLoginSuccess.Invoke(rsp.UserId);
好

2022-07-01 07:10 UTC, lmangit commented on Assets/Src/Framework/UI/UIExtension.cs
>  {
ok

2022-07-01 07:51 UTC, wxq127 approved these changes

2022-07-01 08:02 UTC, merged