feat: add animation component
Meland-Inc/meland-unity pull request #43
Opened 2022-06-15 07:50 UTC by a412555466

2022-06-22 07:09 UTC, wxq127 requested changes

2022-06-22 07:09 UTC, wxq127 commented on Assets/Src/Module/Animation/SpineAnimationCpt.cs
> +        TrackEntry curEntry = _animationState.GetCurrent(trackIndex);
如果没有初始化呢 这里就报错了

2022-06-22 07:09 UTC, wxq127 commented on Assets/Src/Module/Animation/AnimationCpt.cs
> +public abstract class AnimationCpt : MonoBehaviour
没有实现任何逻辑为什么不是接口呢 上次我们交流是要用接口 这里这样改的思考是什么呢

2022-06-22 11:46 UTC, a412555466 commented on Assets/Src/Module/Animation/AnimationCpt.cs
> +    /// 动画排队播放
这个是专门播放一组连续动画的如果上一个循环，就不会往下播，

2022-06-22 11:47 UTC, a412555466 commented on Assets/Src/Module/Animation/AnimationCpt.cs
> +    public abstract void PlayAnim(string animationName, bool loop = false, float timeScale = 1f);
SpineAnimationCpt里面的PlayAnim可以实现分层的效果

2022-06-22 11:47 UTC, a412555466 commented on Assets/Src/Module/Animation/AnimationCpt.cs
> +    /// 动画事件监听
ok，我加一下

2022-06-22 11:47 UTC, a412555466 commented on Assets/Src/Module/Animation/SpineAnimationCpt.cs
> +using System.Collections.Generic;
好

2022-06-22 11:47 UTC, a412555466 commented on Assets/Src/Module/Animation/SpineAnimationCpt.cs
> +    public void Init(object skeletonAnim)
之前放到基类里面，我改改

2022-06-22 11:48 UTC, a412555466 commented on Assets/Src/Module/Animation/SpineAnimationCpt.cs
> +            SpineAnimationInfo info = SpineAnimationInfo.Create(trackIndex, animationName, loop, timeScale);
OK

2022-06-22 11:48 UTC, a412555466 commented on Assets/Src/Module/Animation/SpineAnimationCpt.cs
> +        entry.TimeScale = timeScale;
不会，这里只会改entry的速度

2022-06-22 11:49 UTC, a412555466 commented on Assets/Src/Module/Animation/AnimationCpt.cs
> +public abstract class AnimationCpt : MonoBehaviour
用抽象组件基类也没啥区别吧，

2022-06-23 06:35 UTC, wxq127 commented on Assets/Src/Module/Animation/AnimationCpt.cs
> +public abstract class AnimationCpt : MonoBehaviour
有区别  说明你还不够理解 接口用少了  用类往往是有一定逻辑在里面 为了子类复用逻辑  但是就必须继承这个类  对于单继承的语言就没法继承其他类  接口是不会阻碍你继承谁 可以任意继承，举个例子假如哪天有个动画播放的组件不是继承mono脚本的  继承xxx的  你这里就有问题了  因为实现方没法重新继承自己想要的  为什么说面向接口编程是有道理的

2022-06-23 06:37 UTC, wxq127 requested changes

2022-06-23 06:37 UTC, wxq127 commented on Assets/Src/Module/Animation/SpineAnimationCpt.cs
> +        if (!IsValid)
加错位置了  应该加到160行 没初始化时我播放的动画为什么就不能停止呢？

2022-06-23 07:48 UTC, wxq127 approved these changes

2022-06-23 07:51 UTC, merged