Fix scene nature bug
Meland-Inc/meland-unity pull request #85
Opened 2022-07-14 10:55 UTC by Zhuozy

-fix MainPlayer Move
-fix GrassCollider
-fix TreeIdle
-Addjust chinese file name

2022-07-14 11:05 UTC, lmangit commented on Assets/Src/SceneArt/TreeIdle.cs
> +            //animationEntry.TimeScale = timeScale;
这个为什么要注释掉

2022-07-18 08:26 UTC, wxq127 requested changes
- 资源按规范存放，看美术规范文档和工程文件夹文档
- 不要有中文名资源
- 代码开发需要按照readme中搭建开发环境保持规范

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/Prefab/ShadowSprite.meta
> +guid: 7d56113f9ac4b4dfc919730be6ef1aae
这里面的东西貌似没用到 确认后删掉

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/Prefab/Paper.meta
> +guid: 126c237aa59c44116826061ff9691049
请按规范存放在SceneAsset

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/SpineRaw.meta
> +guid: 4270a11f0b98e4ebca3ae506cea011b0
我记得这个文件夹我都删掉了  你解决冲突又弄回来了？

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/Prefab/Spine/spine project.meta
> +guid: ee0f192616c29435991928a8892214b7
这个文件夹和命名有什么意义？

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/Prefab/Spine/spine project/c3/c3.png.meta
> +guid: 7f1b6982e9604480db06631d16f57a43
请按规范存放

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/Prefab/Spine/spine project/c3/c3_Material.mat.meta
> +guid: 74a19200d44c34525819463a7c0db3a0
请按规范存放

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/Models/cj1.fbx.meta
> +guid: 92161168a3eb72049a4e5beadbad4a44
不允许正式资源这么大型复杂的单一模型文件，浪费程序性能，程序即使看不到的元素也会一起加载上来

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/SceneAsset/Prefab/Nature/SourceAsset/023.png.meta
> +guid: f2a175462ff029142a5c416ac19722a7
请按规范存放

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/SceneAsset/Prefab/Nature/SourceAsset/未标题-1.png.meta
> +guid: 43de5eb54e7067946820bec1f3e28f37
不允许中文

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/Textures/07.png.meta
> +guid: cea3739501e70c147b7f044ae78b3f98
没用到的不要放进来 自行检查

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/Textures/NewLayer 4.terrainlayer.meta
> +guid: c30322ac71a2f6545a3ddc65f2e17e0b
请按规范存放

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/element/未标题-1.png.meta
> +guid: d673a916857f38548a29d791a1ae5e65
不允许中文名

2022-07-18 08:26 UTC, wxq127 commented on Assets/RawResource/element.meta
> +guid: 21f7e8e04b19f4d45a52d0bd270c8909
请按规范存放 不要私自在根节点创建文件夹

2022-07-18 13:18 UTC, Zhuozy commented on Assets/Src/SceneArt/GrassCollider.cs
> +    public void OnTriggerEnter(){
是的，边缘反复碰撞反复触发。

2022-07-27 06:14 UTC, closed without merging