arrange:code arrange:add slot data cpt & profile data cpt
Meland-Inc/meland-unity pull request #88
Opened 2022-07-18 05:56 UTC by lmangit

2022-07-20 01:32 UTC, wxq127 requested changes
挺不错，随时整理自己代码

2022-07-20 01:32 UTC, wxq127 commented on Assets/Src/Module/Backpack/BackpackRoleViewLogic.cs
> +            item.Value.SetSlotData(slotDic[item.Key]);
原则上不要取一样的变量 不要乱用this来区分  像这行代码别人就可能困扰

2022-07-20 01:32 UTC, wxq127 commented on Assets/Src/Module/Entity/Data/RoleProfileData.cs
> +        Message.RoleProfileUpdated.Invoke(field);//TODO:需要优化，可能一次性更新多个属性，没必要每次都触发
给个可选参数 是否广播  默认true就好了

2022-07-20 01:32 UTC, wxq127 commented on Assets/Src/Module/Network/Channel/GameChannel/Action/UpgradePlayerLevelAction.cs
> +        DataManager.MainPlayer.Role.GetComponent<RoleProfileData>().UpdateProfile(EntityProfileField.EntityProfileFieldLv, rsp.CurLevel);
养成习惯 不要连续get同样组件

2022-07-25 05:35 UTC, lmangit commented on Assets/Src/Module/Network/Channel/GameChannel/Action/UpgradePlayerLevelAction.cs
> +        DataManager.MainPlayer.Role.GetComponent<RoleProfileData>().UpdateProfile(EntityProfileField.EntityProfileFieldLv, rsp.CurLevel);
1

2022-07-25 05:35 UTC, lmangit commented on Assets/Src/Module/Entity/Data/RoleProfileData.cs
> +        Message.RoleProfileUpdated.Invoke(field);//TODO:需要优化，可能一次性更新多个属性，没必要每次都触发
1

2022-07-25 05:35 UTC, lmangit commented on Assets/Src/Module/Backpack/BackpackRoleViewLogic.cs
> +            item.Value.SetSlotData(slotDic[item.Key]);
1

2022-07-26 03:42 UTC, wxq127 approved these changes

2022-07-26 03:55 UTC, merged