basic ui framework:realize UI framework by fgui
Meland-Inc/meland-unity pull request #9
Opened 2022-05-17 06:44 UTC by lmangit

2022-05-18 03:39 UTC, wxq127 requested changes
- 点赞：学习很快，写的也很规范

2022-05-18 03:39 UTC, wxq127 commented on Assets/Src/Framework/UI/FGUIFormHelper.cs
> +        Destroy((Object)uiFormInstance);
需要将uiFormInstance置空  否则对象不会回收

2022-05-18 03:39 UTC, wxq127 commented on Assets/Src/Framework/UI/FGUILogicCpt.cs
> +        GComponent child = GCom.GetChild(childName).asCom;
这个和上面有个类似评论  子添加逻辑为什么还要我来给他添加 不知道是不是有特殊用意

2022-05-18 03:39 UTC, wxq127 commented on Assets/Src/Framework/UI/FGUIManagerCenter.cs
> +            { eFormID.main,  "FormTest" }
这个value是什么 资源名吗 还是UIname   从 _dicForm名和注释上都体现不出

2022-05-18 03:39 UTC, wxq127 commented on Assets/Src/Framework/UI/FGUIManagerCenter.cs
> +            return string.Format("{0}{1}.prefab", FORM_ASSET_PREFIX, value);
其实有新的更简洁维护的写法 不过我现在还不知道差别 $"{xxx}yyy" 这里可以不改 我只提一嘴

2022-05-18 03:39 UTC, wxq127 commented on Assets/Src/Framework/UI/FGUIManagerCenter.cs
> +        if (_dicFormSerialID.TryGetValue(formID, out int value))
没看到这个赋值过 不知道干嘛的

2022-05-18 03:39 UTC, wxq127 commented on Assets/Src/Framework/UI/UIExtension.cs
> +    private static int OpenUIForm(this UIComponent uiCom, eFormID formID, string groupName)
扩展用的很顺手嘛

2022-05-18 03:45 UTC, lmangit commented on Assets/Src/Framework/UI/FGUIForm.cs
> +    public T AddUILogicCpt<T>(GComponent child) where T : FGUILogicCpt, new()
有想过，但又尽量不想改源码，不过被你一说的确觉得有点绕，我再想想

2022-05-18 05:30 UTC, lmangit commented on Assets/Src/Framework/UI/FGUIForm.cs
> +    public T AddUILogicCpt<T>(GComponent child) where T : FGUILogicCpt, new()
对哦，我扩展GComponent不就好了

2022-05-23 02:15 UTC, lmangit commented on Assets/Src/Framework/UI/FGUIDefine.cs
> +namespace FGUIDefine
好

2022-05-23 02:28 UTC, lmangit commented on Assets/Src/Framework/UI/FGUIFormHelper.cs
> +        Destroy((Object)uiFormInstance);
局部变量，用它的业务处关注就好

2022-05-23 02:28 UTC, lmangit commented on Assets/Src/Framework/UI/FGUILogicCpt.cs
> +        GComponent child = GCom.GetChild(childName).asCom;
已改

2022-05-23 02:28 UTC, lmangit commented on Assets/Src/Framework/UI/FGUIManagerCenter.cs
> +            { eFormID.main,  "FormTest" }
我更新下命名

2022-05-23 02:37 UTC, lmangit commented on Assets/Src/Framework/UI/FGUIDefine.cs
> +        public static string Form = "Form";
已改

2022-05-23 09:05 UTC, closed without merging